USE study;

CREATE TABLE PRIOR_ACT (
    PRIOR_ID INT NOT NULL AUTO_INCREMENT,
    ACTIVITY_ID INT NOT NULL,
    PRIOR_PROB DECIMAL(5,4) CHECK (PRIOR_PROB >= 0 AND PRIOR_PROB <= 1),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (PRIOR_ID),
    FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITY(ACTIVITY_ID) ON DELETE CASCADE
);

CREATE TABLE POSTERIOR_ACT (
    POSTERIOR_ID INT NOT NULL AUTO_INCREMENT,
    PRIOR_ID INT NOT NULL,
    LEARNING DECIMAL(5,4) CHECK (LEARNING >= 0 AND LEARNING <= 1),
    OVERVIEW DECIMAL(5,4) CHECK (OVERVIEW >= 0 AND OVERVIEW <= 1),
    PRACTICE DECIMAL(5,4) CHECK (PRACTICE >= 0 AND PRACTICE <= 1),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (POSTERIOR_ID),
    FOREIGN KEY (PRIOR_ID) REFERENCES PRIOR_ACT(PRIOR_ID) ON DELETE CASCADE
);

CREATE TABLE TARGET_TIME (
    TARGET_TIME_ID INT NOT NULL AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    DAY_ID INT NOT NULL,
    TARGET_MIN FLOAT,
    PRIMARY KEY (TARGET_TIME_ID),
    FOREIGN KEY (USER_ID) REFERENCES `USERS`(USER_ID) ON DELETE CASCADE, 
    FOREIGN KEY (DAY_ID) REFERENCES `DAY`(DAY_ID) ON DELETE CASCADE
);