CREATE DATABASE IF NOT EXISTS study;
USE study;

-- USER Table
CREATE TABLE USER (
    USER_ID VARCHAR(10) PRIMARY KEY,
    NAME NVARCHAR(100),
    BIRTH DATE,
    GENDER NVARCHAR(10),
    MAJOR NVARCHAR(100)
);

-- ACTIVITY Table
CREATE TABLE ACTIVITY (
    ACTIVITY_ID VARCHAR(10) PRIMARY KEY,
    CATEGORY NVARCHAR(100),
    SUBCATEGORY NVARCHAR(100),
    SUBSUBCATE NVARCHAR(100),
    TYPE NVARCHAR(100),
    TIME_CONSTRAINT BOOLEAN,
    IS_SCORED BOOLEAN,
    AIM_MIN INT
);

-- ACTIVITY_LOG Table
CREATE TABLE ACTIVITY_LOG (
    LOG_ID VARCHAR(10) PRIMARY KEY,
    USER_ID VARCHAR(10),
    ACTIVITY_ID VARCHAR(10),
    TIMESTAMP DATE,
    DEVICE NVARCHAR(100),
    LOCATION NVARCHAR(100),
    WEATHER NVARCHAR(100),
    TEMPERATURE FLOAT,
    MOOD NVARCHAR(100),
    HEALTH NVARCHAR(100),
    ENERGY NVARCHAR(100),
    SLEEP_HOURS FLOAT,
    FOOD_INTAKE NVARCHAR(100),
    LIGHT BOOLEAN,
    MUSIC BOOLEAN,
    COMPLETEDTIME DATE,
    LEVELRATED NVARCHAR(100),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITY(ACTIVITY_ID)
);

-- PERFORMANCE_SCORE Table
CREATE TABLE PERFORMANCE_SCORE (
    PERSCORE_ID VARCHAR(10) PRIMARY KEY,
    LOG_ID VARCHAR(10),
    SCORE_TYPE NVARCHAR(100),
    VALUE FLOAT,
    UNIT NVARCHAR(100),
    TARGET_MET BOOLEAN,
    FOREIGN KEY (LOG_ID) REFERENCES ACTIVITY_LOG(LOG_ID)
);