@startuml
title LearningDB
left to right direction
actor "Bang Nguyen" as me

rectangle "LearningDB" {
    usecase "Nhập dữ liệu"
    usecase "Hiển thị Dashboard"
    usecase "Eating"
    usecase "Activity"
    usecase "Sleep"
    usecase "Shower"
}
me --> "Nhập dữ liệu"
"Nhập dữ liệu" --> "Eating"
"Nhập dữ liệu" --> "Activity"
"Nhập dữ liệu" --> "Sleep"
"Nhập dữ liệu" --> "Shower"
me --> "Hiển thị Dashboard"
@enduml