-- Create the database
-- DROP DATABASE IF EXISTS BigBrain;
-- CREATE DATABASE BigBrain;
-- Select the database

USE mysql;

-- USER Table
CREATE TABLE `USER` (
    USER_ID VARCHAR(10) PRIMARY KEY,
    NAME VARCHAR(100),
    BIRTH DATE,
    GENDER VARCHAR(10),
    MAJOR VARCHAR(100)
);

-- ACTIVITY Table
CREATE TABLE ACTIVITY (
    ACTIVITY_ID VARCHAR(10) PRIMARY KEY,
    CATEGORY VARCHAR(100),
    SUBCATEGORY VARCHAR(100),
    SUBSUBCATE VARCHAR(100),
    TYPE VARCHAR(100),
    TIME_CONSTRAINT BOOLEAN,
    IS_SCORED BOOLEAN,
    AIM_MIN INT
);

-- ACTIVITY_LOG Table
CREATE TABLE ACTIVITY_LOG (
    USER_ID VARCHAR(10) NOT NULL,
    ACTIVITY_ID VARCHAR(10) NOT NULL,
    TIMESTAMP DATETIME NOT NULL,
    DEVICE VARCHAR(100),
    LOCATION VARCHAR(100),
    WEATHER VARCHAR(100),
    TEMPERATURE FLOAT,
    MOOD VARCHAR(100),
    HEALTH VARCHAR(100),
    ENERGY VARCHAR(100),
    SLEEP_HOURS FLOAT,
    FOOD_INTAKE VARCHAR(100),
    LIGHT BOOLEAN,
    MUSIC BOOLEAN,
    COMPLETEDTIME DATETIME,
    LEVELRATED VARCHAR(100),
    PRIMARY KEY (USER_ID, ACTIVITY_ID, TIMESTAMP),
    FOREIGN KEY (USER_ID) REFERENCES `USER`(USER_ID),
    FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITY(ACTIVITY_ID)
);

-- PERFORMANCE_SCORE Table
CREATE TABLE PERFORMANCE_SCORE (
    USER_ID VARCHAR(10) NOT NULL,
    ACTIVITY_ID VARCHAR(10) NOT NULL,
    TIMESTAMP DATETIME NOT NULL,
    SCORE_TYPE VARCHAR(100) NOT NULL,
    VALUE FLOAT,
    UNIT VARCHAR(100),
    TARGET_MET BOOLEAN,
    PRIMARY KEY (USER_ID, ACTIVITY_ID, TIMESTAMP, SCORE_TYPE),
    FOREIGN KEY (USER_ID, ACTIVITY_ID, TIMESTAMP)
        REFERENCES ACTIVITY_LOG(USER_ID, ACTIVITY_ID, TIMESTAMP)
);