CREATE TABLE MONHOC (
    MAMH INT PRIMARY KEY,
    TENMH NVARCHAR(100),
    HOCKI INT
);

CREATE TABLE SINHVIEN (
    MSSV INT PRIMARY KEY,
    HOTEN NVARCHAR(100),
    GPA FLOAT,
    XEPLOAI NVARCHAR(50)
);

CREATE TABLE KETQUA (
    MSSV INT,
    MAMH INT,
    DIEM FLOAT,
    PRIMARY KEY (MSSV, MAMH),
    FOREIGN KEY (MSSV) REFERENCES SINHVIEN(MSSV),
    FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
);

ALTER TABLE MONHOC
ADD TINCHI INT;

ALTER TABLE MONHOC
ALTER COLUMN MAMH VARCHAR(6) NOT NULL;

ALTER TABLE SINHVIEN
ALTER COLUMN MSSV VARCHAR(10) NOT NULL;

ALTER TABLE MONHOC
ADD CONSTRAINT PK_MONHOC PRIMARY KEY (MAMH);

ALTER TABLE SINHVIEN
ADD CONSTRAINT PK_SINHVIEN PRIMARY KEY (MSSV);

-- KETQUA chinh sua khoa

ALTER TABLE KETQUA
ALTER COLUMN MSSV VARCHAR(10) NOT NULL;

ALTER TABLE KETQUA
ALTER COLUMN MAMH VARCHAR(6) NOT NULL;

ALTER TABLE KETQUA
ADD CONSTRAINT KETQUA_MONHOC_SINHVIEN_PK PRIMARY KEY (MSSV, MAMH);

ALTER TABLE KETQUA
ADD FOREIGN KEY (MSSV) REFERENCES SINHVIEN(MSSV);

ALTER TABLE KETQUA
ADD FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH);

-- Them kien thuc hoc phan

ALTER TABLE MONHOC
ADD KIENTHUC NVARCHAR(50);