-- INPUT DATABASE for MONHOC
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('861301', N'Triết học Mác - Lênin', 1, 3);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('861302', N'Kinh tế chính trị Mác - Lênin', 2, 2);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('861303', N'Chủ nghĩa xã hội khoa học', 3, 2);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('861304', N'Tư tưởng Hồ Chí Minh', 4, 2);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('861305', N'Lịch sử Đảng Cộng sản Việt Nam', 5, 2);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('865006', N'Pháp luật đại cương', 1, 2);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('866401', N'Tiếng Anh (I)', 2, 3);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('866402', N'Tiếng Anh (II)', 3, 3);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('866403', N'Tiếng Anh (III)', 4, 3);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('862101', N'Giáo dục thể chất (I)', 1, 1);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('862406', N'Giáo dục quốc phòng và an ninh I', 1, 2);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('862407', N'Giáo dục quốc phòng và an ninh II', 2, 2);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('862408', N'Giáo dục quốc phòng và an ninh III', 3, 2);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('862409', N'Giáo dục quốc phòng và an ninh IV', 4, 4);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('BOBA11', N'Bóng bàn 1', 1, 1);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('BODA11', N'Bóng đá 1', 1, 1);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('BOCH11', N'Bóng chuyền 1', 1, 1);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('BORO11', N'Bóng rổ 1', 1, 1);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('CALO11', N'Cầu lông 1', 1, 1);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('BOBA12', N'Bóng bàn 2', 2, 1);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('BODA12', N'Bóng đá 2', 2, 1);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('BOCH12', N'Bóng chuyền 2', 2, 1);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('BORO12', N'Bóng rổ 2', 2, 1);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('CALO12', N'Cầu lông 2', 2, 1);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('801351', N'Phương pháp NCKH cho ngành Toán', 6, 2);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('801401', N'Đại số tuyến tính', 1, 6);
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI)
VALUES ('848001', N'Giải tích hàm một biến', 2, 6);