CREATE DATABASE BigBrain;
GO

USE BigBrain;
GO

-- USER Table
CREATE TABLE [USER] (
    USER_ID VARCHAR(10) PRIMARY KEY,
    NAME NVARCHAR(100) NULL,
    BIRTH DATE NULL,
    GENDER NVARCHAR(10) NULL,
    MAJOR NVARCHAR(100) NULL
);

-- ACTIVITY Table
CREATE TABLE ACTIVITY (
    ACTIVITY_ID VARCHAR(10) PRIMARY KEY,
    CATEGORY NVARCHAR(100) NULL,
    SUBCATEGORY NVARCHAR(100) NULL,
    SUBSUBCATE NVARCHAR(100) NULL,
    TYPE NVARCHAR(100) NULL,
    TIME_CONSTRAINT BIT NULL,
    IS_SCORED BIT NULL,
    AIM_MIN INT NULL
);

-- ACTIVITY_LOG Table
CREATE TABLE ACTIVITY_LOG (
    USER_ID VARCHAR(10) NOT NULL,
    ACTIVITY_ID VARCHAR(10) NOT NULL,
    TIMESTAMP DATETIME NOT NULL,
    DEVICE NVARCHAR(100) NULL,
    LOCATION NVARCHAR(100) NULL,
    WEATHER NVARCHAR(100) NULL,
    TEMPERATURE FLOAT NULL,
    MOOD NVARCHAR(100) NULL,
    HEALTH NVARCHAR(100) NULL,
    ENERGY NVARCHAR(100) NULL,
    SLEEP_HOURS FLOAT NULL,
    FOOD_INTAKE NVARCHAR(100) NULL,
    LIGHT BIT NULL,
    MUSIC BIT NULL,
    COMPLETEDTIME DATETIME NULL,
    LEVELRATED NVARCHAR(100) NULL,
    PRIMARY KEY (USER_ID, ACTIVITY_ID, TIMESTAMP),
    FOREIGN KEY (USER_ID) REFERENCES [USER](USER_ID),
    FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITY(ACTIVITY_ID)
);

-- PERFORMANCE_SCORE Table
CREATE TABLE PERFORMANCE_SCORE (
    USER_ID VARCHAR(10) NOT NULL,
    ACTIVITY_ID VARCHAR(10) NOT NULL,
    TIMESTAMP DATETIME NOT NULL,
    SCORE_TYPE NVARCHAR(100) NOT NULL,
    VALUE FLOAT NULL,
    UNIT NVARCHAR(100) NULL,
    TARGET_MET BIT NULL,
    PRIMARY KEY (USER_ID, ACTIVITY_ID, TIMESTAMP, SCORE_TYPE),
    FOREIGN KEY (USER_ID, ACTIVITY_ID, TIMESTAMP)
        REFERENCES ACTIVITY_LOG(USER_ID, ACTIVITY_ID, TIMESTAMP)
);