USE study;
GO

-- CREATE TABLE MONHOC (
--     MAMH VARCHAR(6) PRIMARY KEY,
--     TENMH NVARCHAR(100),
--     HOCKI INT,
--     TINCHI INT,
--     KIENTHUC NVARCHAR(20)
-- );

-- CREATE TABLE SINHVIEN (
--     MSSV VARCHAR(10) PRIMARY KEY,
--     HOTEN NVARCHAR(100),
--     GPA FLOAT,
--     XEPLOAI NVARCHAR(50)
-- );

-- CREATE TABLE KETQUA (
--     MSSV VARCHAR(10) NOT NULL,
--     MAMH VARCHAR(6) NOT NULL,
--     DIEM FLOAT,
--     PRIMARY KEY (MSSV, MAMH),
--     FOREIGN KEY (MSSV) REFERENCES SINHVIEN(MSSV),
--     FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
-- );

EXEC sp_rename 'KETQUA.DIEM', 'DIEM_HE10', 'COLUMN';

ALTER TABLE KETQUA
ADD DIEM_HE4 FLOAT,
    DIEM_CHU VARCHAR(1);

ALTER TABLE SINHVIEN
DROP COLUMN GPA, XEPLOAI;

ALTER TABLE SINHVIEN
ADD KHOA INT;

-- Table DKMH

CREATE TABLE DKMH (
    MAMH VARCHAR(6),
    NGDK DATE,
    NHOM VARCHAR(2),
    THU INT,
    TIETBD INT,
    SOTIET INT,
    PHONG VARCHAR(10),
    GVIEN NVARCHAR(100),
    PRIMARY KEY (MAMH, NGDK, NHOM),
    FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
)

ALTER TABLE DKMH
DROP CONSTRAINT PK__DKMH__4DD3994668E6676B;

ALTER TABLE DKMH
ALTER COLUMN THU INT NOT NULL;

ALTER TABLE DKMH
ADD CONSTRAINT PK_THU PRIMARY KEY (MAMH, NGDK, NHOM, THU);