USE study;
GO

-- Các môn học trong kỳ này
-- 841044
-- 841109
-- 841110
-- 848403
-- 861303
-- 862409

SELECT *
FROM MONHOC
WHERE KIENTHUC LIKE 'GDDC'

-- Subject have been completed
SELECT MH.MAMH, MH.TENMH
FROM KETQUA KQ JOIN MONHOC MH ON KQ.MAMH = MH.MAMH

-- Subject haven't been done (GGDC)

SELECT MAMH, TENMH, HOCKI
FROM MONHOC
WHERE MAMH NOT IN (
    SELECT MAMH
    FROM KETQUA
    WHERE DIEM_HE10 IS NOT NULL
) AND
(KIENTHUC LIKE 'GDDC') AND
(MONHOC.MAMH NOT LIKE '841044') AND
(MONHOC.MAMH NOT LIKE '841109') AND
(MONHOC.MAMH NOT LIKE '841110') AND
(MONHOC.MAMH NOT LIKE '848403') AND
(MONHOC.MAMH NOT LIKE '861303') AND
(MONHOC.MAMH NOT LIKE '862409')

-- Mon D
SELECT MONHOC.MAMH, TENMH
FROM MONHOC JOIN KETQUA ON MONHOC.MAMH = KETQUA.MAMH
WHERE DIEM_CHU LIKE 'D'

USE study;
GO

SELECT TENMH, DKMH.MAMH, NHOM, THU, TIETBD, SOTIET, PHONG, GVIEN
FROM DKMH JOIN MONHOC ON DKMH.MAMH = MONHOC.MAMH
WHERE
(DKMH.MAMH LIKE '861304')
AND
(GVIEN NOT LIKE N'%Vĩnh%')
AND
(GVIEN NOT LIKE N'%Quyên%')
-- AND
-- (
--     (TIETBD BETWEEN 3 AND 5)
--     OR 
--     (TIETBD BETWEEN 8 AND 10)
-- )
ORDER BY THU

-- Đăng ký môn học HK3 2025

SELECT TENMH, DKMH.MAMH, NHOM, THU, TIETBD, SOTIET, PHONG, GVIEN
FROM DKMH JOIN MONHOC ON DKMH.MAMH = MONHOC.MAMH
WHERE
((DKMH.MAMH LIKE '861305')
AND
(NHOM = '03' OR NHOM = '04'))
OR
((DKMH.MAMH LIKE '861304')
AND
(NHOM = '07' OR NHOM = '06'))
OR
((DKMH.MAMH LIKE 'BORO11')
AND
(NHOM = '02' OR NHOM = '05'))

SELECT TENMH, DKMH.MAMH, NHOM, THU, TIETBD, SOTIET, PHONG, GVIEN
FROM DKMH JOIN MONHOC ON DKMH.MAMH = MONHOC.MAMH
WHERE
((DKMH.MAMH LIKE '861305')
AND
(NHOM = '04'))