USE study;
GO

-- Các môn học trong kỳ này
-- 841044
-- 841109
-- 841110
-- 848403
-- 861303
-- 862409

SELECT *
FROM MONHOC
WHERE KIENTHUC LIKE 'GDDC'

-- Subject have been completed
SELECT MH.MAMH, MH.TENMH
FROM KETQUA KQ JOIN MONHOC MH ON KQ.MAMH = MH.MAMH

-- Subject haven't been done (GGDC)

SELECT MAMH, TENMH, HOCKI
FROM MONHOC
WHERE MAMH NOT IN (
    SELECT MAMH
    FROM KETQUA
    WHERE DIEM_HE10 IS NOT NULL
) AND
(KIENTHUC LIKE 'GDDC') AND
(MONHOC.MAMH NOT LIKE '841044') AND
(MONHOC.MAMH NOT LIKE '841109') AND
(MONHOC.MAMH NOT LIKE '841110') AND
(MONHOC.MAMH NOT LIKE '848403') AND
(MONHOC.MAMH NOT LIKE '861303') AND
(MONHOC.MAMH NOT LIKE '862409')

-- Mon D
SELECT MONHOC.MAMH, TENMH
FROM MONHOC JOIN KETQUA ON MONHOC.MAMH = KETQUA.MAMH
WHERE DIEM_CHU LIKE 'D'

SELECT *
FROM DKMH
WHERE THU = 2