USE study;
GO

-- INPUT DATABASE for MONHOC
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('861301', N'Triết học Mác - Lênin', 1, 3, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('861302', N'Kinh tế chính trị Mác - Lênin', 2, 2, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('861303', N'Chủ nghĩa xã hội khoa học', 3, 2, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('861304', N'Tư tưởng Hồ Chí Minh', 4, 2, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('861305', N'Lịch sử Đảng Cộng sản Việt Nam', 4, 2, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('865006', N'Pháp luật đại cương', 1, 2, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('866401', N'Tiếng Anh (I)', 2, 3, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('866402', N'Tiếng Anh (II)', 3, 3, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('866403', N'Tiếng Anh (III)', 4, 3, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('862101', N'Giáo dục thể chất (I)', 1, 1, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('862406', N'Giáo dục quốc phòng và an ninh I', 1, 3, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('862407', N'Giáo dục quốc phòng và an ninh II', 2, 2, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('862408', N'Giáo dục quốc phòng và an ninh III', 3, 2, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('862409', N'Giáo dục quốc phòng và an ninh IV', 4, 4, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('BOBA11', N'Bóng bàn 1', 2, 1, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('BODA11', N'Bóng đá 1', 2, 1, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('BOCH11', N'Bóng chuyền 1', 2, 1, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('BORO11', N'Bóng rổ 1', 2, 1, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('CALO11', N'Cầu lông 1', 2, 1, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('BOBA12', N'Bóng bàn 2', 3, 1, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('BODA12', N'Bóng đá 2', 3, 1, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('BOCH12', N'Bóng chuyền 2', 3, 1, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('BORO12', N'Bóng rổ 2', 3, 1, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('CALO12', N'Cầu lông 2', 3, 1, 'GDDC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('801351', N'Phương pháp NCKH cho ngành Toán', 7, 2, 'KTCS');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('801401', N'Đại số tuyến tính', 1, 5, 'KTCS');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848001', N'Giải tích hàm một biến', 1, 6, 'KTCS');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848002', N'Giải tích hàm nhiều biến', 2, 6, 'KTCS');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('801145', N'Xác suất và thống kê toán', 2, 3, 'KTCS');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('801043', N'Cơ sở Toán học hiện đại', 1, 2, 'KTCS');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848010', N'Giải tích số', 3, 4, 'KTN_BB');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('801047', N'Giải tích hàm', 5, 4, 'KTN_BB');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('801046', N'Độ đo tích phân', 4, 4, 'KTN_BB');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848011', N'Thống kê ứng dụng', 3, 4, 'KTN_BB');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848410', N'Quy hoạch tuyến tính', 2, 3, 'KTN_BB');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848098', N'Thực tập tốt nghiệp', 8, 5, 'KTN_BB');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848099', N'Khoá luận tốt nghiệp', 8, 10, 'KTN_BB');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('841076', N'Công nghệ phần mềm nâng cao', 8, 3, 'TTKL');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848415', N'Kiểm thử phần mềm', 8, 3, 'TTKL');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848416', N'Khai thác dữ liệu', 8, 3, 'TTKL');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848412', N'Máy học', 8, 4, 'TTKL');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('801078', N'Phương trình đạo hàm riêng', 8, 3, 'TTKL');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848022', N'Giải tích số nâng cao', 8, 4, 'TTKL');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('801077', N'Phương trình toán lý', 8, 3, 'TTKL');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848015', N'Lập trình .Net', 8, 3, 'TTKL');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848024', N'Bảo mật mạng máy tính', 8, 3, 'TTKL');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848301', N'Seminar chuyên đề tin học 2', 8, 2, 'TTKL');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('801069', N'Vận trù học', 3, 2, 'KTN_TC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848402', N'Phương trình vi phân và ứng dụng', 4, 3, 'KTN_TC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848012', N'Thực hành Laboratory', 3, 3, 'KTN_TC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('801028', N'Bài toán không chỉnh', 6, 3, 'KTN_TC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('801304', N'Lý thuyết ổn định', 6, 4, 'KTN_TC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('801079', N'Giải tích phi tuyến', 6, 3, 'KTN_TC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848039', N'Lý thuyết trò chơi và ứng dụng', 5, 3, 'CN_BB');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848411', N'Kỹ thuật lập trình', 4, 4, 'CN_BB');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('841108', N'Cấu trúc dữ liệu và giải thuật', 5, 4, 'CN_BB');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('841403', N'Cấu trúc rời rạc', 5, 4, 'CN_BB');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('841109', N'Cơ sở dữ liệu', 6, 4, 'CN_BB');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('841048', N'Phân tích thiết kế hệ thống thông tin', 7, 4, 'CN_BB');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('841110', N'Cơ sở trí tuệ nhân tạo', 6, 4, 'CN_BB');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('841044', N'Phương pháp lập trình hướng đối tượng', 6, 4, 'CN_BB');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('841047', N'Công nghệ phần mềm', 7, 4, 'CN_BB');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848403', N'Phép biến đổi tích phân', 6, 4, 'CN_TC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848109', N'Lý thuyết mật mã', 5, 4, 'CN_TC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848028', N'Phân tích xử lý ảnh', 7, 4, 'CN_TC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('841022', N'Hệ điều hành', 5, 3, 'CN_TC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848304', N'Quy hoạch phi tuyến', 7, 3, 'CN_TC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848050', N'Giải tích lồi và tối ưu', 5, 3, 'CN_TC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('801070', N'Thuật toán tối ưu', 6, 3, 'CN_TC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848404', N'Lập trình game', 7, 3, 'CN_TC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848017', N'Lập trình Web', 7, 4, 'CN_TC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848405', N'Phát triển ứng dụng trên thiết bị di động', 7, 3, 'CN_TC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848406', N'Phát triển ứng dụng internet of things', 7, 3, 'CN_TC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848306', N'Đại số máy tính và cơ sở grobner', 6, 3, 'CN_TC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('841107', N'Lập trình Java', 7, 4, 'CN_TC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848013', N'Kiến trúc máy tính và mạng máy tính', 5, 3, 'CN_TC');
INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('848307', N'Seminar chuyên đề tin học 1', 7, 2, 'CN_TC');

-- Chinh sua MAMH csthdd va ham bien phuc

UPDATE MONHOC
SET MAMH = '801403'
WHERE MAMH = '801043';

INSERT INTO MONHOC (MAMH, TENMH, HOCKI, TINCHI, KIENTHUC)
VALUES ('801043', N'Hàm biến phức', 3, 4, 'KTN_TC');