USE study;
GO

-- CREATE TABLE MONHOC (
--     MAMH VARCHAR(6) PRIMARY KEY,
--     TENMH NVARCHAR(100),
--     HOCKI INT,
--     TINCHI INT,
--     KIENTHUC NVARCHAR(20)
-- );

-- CREATE TABLE SINHVIEN (
--     MSSV VARCHAR(10) PRIMARY KEY,
--     HOTEN NVARCHAR(100),
--     GPA FLOAT,
--     XEPLOAI NVARCHAR(50)
-- );

-- CREATE TABLE KETQUA (
--     MSSV VARCHAR(10) NOT NULL,
--     MAMH VARCHAR(6) NOT NULL,
--     DIEM FLOAT,
--     PRIMARY KEY (MSSV, MAMH),
--     FOREIGN KEY (MSSV) REFERENCES SINHVIEN(MSSV),
--     FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
-- );

EXEC sp_rename 'KETQUA.DIEM', 'DIEM_HE10', 'COLUMN';

ALTER TABLE KETQUA
ADD DIEM_HE4 FLOAT,
    DIEM_CHU VARCHAR(1);

ALTER TABLE SINHVIEN
DROP COLUMN GPA, XEPLOAI;

ALTER TABLE SINHVIEN
ADD KHOA INT;