USE study
GO

SELECT *
FROM MONHOC
WHERE TENMH LIKE N'%Phép biến đổi%'

SELECT *
FROM MONHOC
WHERE KIENTHUC LIKE 'TTKL'

SELECT MAMH
FROM MONHOC
WHERE TENMH LIKE N'cơ sở dữ liệu'

SELECT DISTINCT KIENTHUC
FROM MONHOC

SELECT TENMH, MAMH, KIENTHUC
FROM MONHOC
WHERE KIENTHUC LIKE 'GDDC'

SELECT TENMH, HOCKI, TINCHI
FROM MONHOC
WHERE KIENTHUC LIKE 'TTKL'
ORDER BY TINCHI DESC

SELECT *
FROM MONHOC LEFT JOIN KETQUA ON KETQUA.MAMH = MONHOC.MAMH

-- FIND SUBJECT STUDIED

SELECT TENMH, TINCHI, HOCKI, MONHOC.MAMH, DIEM_HE10
FROM MONHOC JOIN KETQUA ON KETQUA.MAMH = MONHOC.MAMH
ORDER BY DIEM_HE10

-- FIND SUBJECT HAVE NOT STUDIED

SELECT TENMH, HOCKI, TINCHI
FROM MONHOC LEFT JOIN KETQUA ON KETQUA.MAMH = MONHOC.MAMH
WHERE KIENTHUC LIKE 'CN_BB' AND DIEM_HE10 IS NULL
ORDER BY HOCKI

SELECT TENMH, HOCKI, TINCHI
FROM MONHOC LEFT JOIN KETQUA ON KETQUA.MAMH = MONHOC.MAMH
WHERE KIENTHUC LIKE 'CN_TC' AND DIEM_HE10 IS NULL
ORDER BY TINCHI DESC

SELECT TENMH, HOCKI, TINCHI
FROM MONHOC LEFT JOIN KETQUA ON KETQUA.MAMH = MONHOC.MAMH
WHERE KIENTHUC LIKE 'GDDC' AND DIEM_HE10 IS NULL

-- GPA ---------------

SELECT TENMH, DIEM_HE10
FROM KETQUA JOIN MONHOC ON KETQUA.MAMH = MONHOC.MAMH
WHERE KETQUA.DIEM_HE4 IS NOT NULL
    AND 
    MONHOC.MAMH NOT LIKE '862101' AND 
    MONHOC.MAMH NOT LIKE '862406' AND
    MONHOC.MAMH NOT LIKE '862407' AND
    MONHOC.MAMH NOT LIKE '862408' AND
    MONHOC.MAMH NOT LIKE '862409' AND
    MONHOC.MAMH NOT LIKE 'BODA11'
ORDER BY DIEM_HE10 DESC

SELECT ((SUM(DIEM_HE10 * TINCHI)/SUM(TINCHI))*4)/10 AS GPA
FROM KETQUA JOIN MONHOC ON KETQUA.MAMH = MONHOC.MAMH
WHERE KETQUA.DIEM_HE10 IS NOT NULL
    AND 
    MONHOC.MAMH NOT LIKE '862101' AND 
    MONHOC.MAMH NOT LIKE '862406' AND
    MONHOC.MAMH NOT LIKE '862407' AND
    MONHOC.MAMH NOT LIKE '862408' AND
    MONHOC.MAMH NOT LIKE '862409' AND
    MONHOC.MAMH NOT LIKE 'BODA11'

-- TU
SELECT SUM(DIEM_HE10 * TINCHI) AS GPA
FROM KETQUA JOIN MONHOC ON KETQUA.MAMH = MONHOC.MAMH
WHERE KETQUA.DIEM_HE10 IS NOT NULL
    AND 
    MONHOC.MAMH NOT LIKE '862101' AND 
    MONHOC.MAMH NOT LIKE '862406' AND
    MONHOC.MAMH NOT LIKE '862407' AND
    MONHOC.MAMH NOT LIKE '862408' AND
    MONHOC.MAMH NOT LIKE '862409' AND
    MONHOC.MAMH NOT LIKE '801401' AND --DSTT
    MONHOC.MAMH NOT LIKE '841403' AND --CTRR
    -- MONHOC.MAMH NOT LIKE '848010' AND --GTS
    MONHOC.MAMH NOT LIKE 'BODA11'
-- MAU
SELECT SUM(TINCHI) AS GPA
FROM KETQUA JOIN MONHOC ON KETQUA.MAMH = MONHOC.MAMH
WHERE KETQUA.DIEM_HE10 IS NOT NULL
    AND 
    MONHOC.MAMH NOT LIKE '862101' AND 
    MONHOC.MAMH NOT LIKE '862406' AND
    MONHOC.MAMH NOT LIKE '862407' AND
    MONHOC.MAMH NOT LIKE '862408' AND
    MONHOC.MAMH NOT LIKE '862409' AND
    MONHOC.MAMH NOT LIKE '801401' AND --DSTT
    MONHOC.MAMH NOT LIKE '841403' AND --CTRR
    -- MONHOC.MAMH NOT LIKE '848010' AND --GTS
    MONHOC.MAMH NOT LIKE 'BODA11'

SELECT TENMH
FROM MONHOC
WHERE MAMH LIKE '801401'