USE study
GO

SELECT *
FROM MONHOC
WHERE TENMH LIKE N'%Phép biến đổi%'

SELECT *
FROM MONHOC
WHERE KIENTHUC LIKE 'TTKL'

SELECT MAMH
FROM MONHOC
WHERE TENMH LIKE N'cơ sở dữ liệu'

SELECT DISTINCT KIENTHUC
FROM MONHOC

SELECT TENMH, HOCKI, TINCHI
FROM MONHOC
WHERE KIENTHUC LIKE 'TTKL'
ORDER BY TINCHI DESC

SELECT TENMH, HOCKI, TINCHI
FROM MONHOC
WHERE KIENTHUC LIKE 'CN_BB'
ORDER BY HOCKI

SELECT TENMH, HOCKI, TINCHI
FROM MONHOC
WHERE KIENTHUC LIKE 'CN_TC'
ORDER BY TINCHI DESC