CREATE DATABASE IF NOT EXISTS school;

USE school;

-- 1. Drop existing tables (if any) to allow clean re-creation
DROP TABLE IF EXISTS `KETQUA`;
DROP TABLE IF EXISTS `DKMH`;
DROP TABLE IF EXISTS `SINHVIEN`;
DROP TABLE IF EXISTS `MONHOC`;

-- 2. MONHOC
CREATE TABLE `MONHOC` (
  `MAMH` VARCHAR(6)    NOT NULL,
  `TENMH` VARCHAR(100) DEFAULT NULL,
  `HOCKI` INT          DEFAULT NULL,
  `TINCHI` INT         DEFAULT NULL,
  `KIENTHUC` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`MAMH`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- 3. SINHVIEN (GPA and XEPLOAI dropped; KHOA added)
CREATE TABLE `SINHVIEN` (
  `MSSV` VARCHAR(10)   NOT NULL,
  `HOTEN` VARCHAR(100) DEFAULT NULL,
  `KHOA` INT           DEFAULT NULL,
  PRIMARY KEY (`MSSV`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- 4. KETQUA
CREATE TABLE `KETQUA` (
  `MSSV` VARCHAR(10)   NOT NULL,
  `MAMH` VARCHAR(6)    NOT NULL,
  `DIEM_HE10` FLOAT    DEFAULT NULL,  -- was DIEM, renamed to DIEM_HE10
  `DIEM_HE4` FLOAT     DEFAULT NULL,  -- added
  `DIEM_CHU` VARCHAR(1) DEFAULT NULL, -- added
  PRIMARY KEY (`MSSV`,`MAMH`),
  KEY `FK_KETQUA_SINHVIEN` (`MSSV`),
  KEY `FK_KETQUA_MONHOC`   (`MAMH`),
  CONSTRAINT `FK_KETQUA_SINHVIEN`
    FOREIGN KEY (`MSSV`) REFERENCES `SINHVIEN` (`MSSV`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_KETQUA_MONHOC`
    FOREIGN KEY (`MAMH`) REFERENCES `MONHOC` (`MAMH`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- 5. DKMH
CREATE TABLE `DKMH` (
  `MAMH` VARCHAR(6)    NOT NULL,
  `NGDK` DATE          NOT NULL,
  `NHOM` VARCHAR(2)    NOT NULL,
  `THU` INT            NOT NULL,     -- altered to NOT NULL
  `TIETBD` INT         DEFAULT NULL,
  `SOTIET` INT         DEFAULT NULL,
  `PHONG` VARCHAR(10)  DEFAULT NULL,
  `GVIEN` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`MAMH`,`NGDK`,`NHOM`,`THU`),  -- original PK dropped and re-added to include THU
  KEY `FK_DKMH_MONHOC` (`MAMH`),
  CONSTRAINT `FK_DKMH_MONHOC`
    FOREIGN KEY (`MAMH`) REFERENCES `MONHOC` (`MAMH`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;