USE quanlydean;
GO

CREATE TABLE NHANVIEN (
    MANV char(9) PRIMARY KEY,
    HONV NVARCHAR(15),
    TENLOT NVARCHAR(15),
    TENNV NVARCHAR(15),
    NGSINH DATE,
    DCHI NVARCHAR(30),
    PHAI NVARCHAR(3),
    LUONG FLOAT,
    MA_NQL CHAR(9),
    PHG int,
    FOREIGN KEY (MA_NQL) REFERENCES NHANVIEN(MANV),
)


CREATE TABLE PHONGBAN (
    MAPHG int PRIMARY KEY,
    TENPHG NVARCHAR(15),
    TRPHG CHAR(9) FOREIGN KEY REFERENCES NHANVIEN(MANV),
    NG_NHANCHUC DATE,
)

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_PHONGBAN
FOREIGN KEY (PHG) REFERENCES PHONGBAN(MAPHG)

CREATE TABLE DEAN (
    MADA int PRIMARY KEY,
    TENDA NVARCHAR(15),
    DDIEM_DA NVARCHAR(15),
    PHONG int FOREIGN KEY REFERENCES PHONGBAN(MAPHG)
)

CREATE TABLE CONGVIEC (
    MADA int,
    STT int,
    TEN_CONG_VIEC nvarchar(50),
    PRIMARY KEY (MADA, STT),
    FOREIGN KEY (MADA) REFERENCES DEAN(MADA)
)

CREATE TABLE PHANCONG (
    MA_NVIEN char(9),
    MADA int,
    STT int,
    THOIGIAN float,
    PRIMARY KEY (MA_NVIEN, MADA, STT),
    FOREIGN KEY (MA_NVIEN) REFERENCES NHANVIEN(MANV),
    FOREIGN KEY (MADA, STT) REFERENCES CONGVIEC(MADA, STT)
)

CREATE TABLE DIADIEM_PHG (
    MAPHG int,
    DIADIEM NVARCHAR(15),
    PRIMARY KEY (MAPHG, DIADIEM),
    FOREIGN KEY (MAPHG) REFERENCES PHONGBAN(MAPHG)
)

CREATE TABLE THANNHAN (
    MA_NVIEN CHAR(9),
    TENTN NVARCHAR(15),
    PHAI NVARCHAR(3),
    NGSINH DATE,
    QUANHE NVARCHAR(15),
    PRIMARY KEY (MA_NVIEN, TENTN),
    FOREIGN KEY (MA_NVIEN) REFERENCES NHANVIEN(MANV)
)